n, m = map(int, input().split())
a = list(map(int, input().split()))
b = list(map(int, input().split()))
giao = sorted(set(a) & set(b))
hieuAB = sorted(set(a) - set(b))
hieuBA = sorted(set(b) - set(a))
for i in giao: print(i, end=" ")
print()
for i in hieuAB: print(i, end=" ")
print()
for i in hieuBA: print(i, end=" ")
